package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentGo;
import com.zbg.secyun.domain.OssComponentGoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssComponentGoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int countByExample(OssComponentGoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByExample(OssComponentGoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insert(OssComponentGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insertSelective(OssComponentGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    List<OssComponentGo> selectByExample(OssComponentGoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    OssComponentGo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentGo record, @Param("example") OssComponentGoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExample(@Param("record") OssComponentGo record, @Param("example") OssComponentGoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_go
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKey(OssComponentGo record);
}