package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentPy;
import com.zbg.secyun.domain.OssComponentPyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssComponentPyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int countByExample(OssComponentPyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByExample(OssComponentPyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insert(OssComponentPy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insertSelective(OssComponentPy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    List<OssComponentPy> selectByExample(OssComponentPyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    OssComponentPy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentPy record, @Param("example") OssComponentPyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExample(@Param("record") OssComponentPy record, @Param("example") OssComponentPyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentPy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_py
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKey(OssComponentPy record);
}