package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentPhp;
import com.zbg.secyun.domain.OssComponentPhpExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssComponentPhpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int countByExample(OssComponentPhpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByExample(OssComponentPhpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insert(OssComponentPhp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insertSelective(OssComponentPhp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    List<OssComponentPhp> selectByExample(OssComponentPhpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    OssComponentPhp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentPhp record, @Param("example") OssComponentPhpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExample(@Param("record") OssComponentPhp record, @Param("example") OssComponentPhpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentPhp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_php
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKey(OssComponentPhp record);
}