package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentCcpp;
import com.zbg.secyun.domain.OssComponentCcppExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssComponentCcppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int countByExample(OssComponentCcppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByExample(OssComponentCcppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insert(OssComponentCcpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insertSelective(OssComponentCcpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    List<OssComponentCcpp> selectByExample(OssComponentCcppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    OssComponentCcpp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentCcpp record, @Param("example") OssComponentCcppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExample(@Param("record") OssComponentCcpp record, @Param("example") OssComponentCcppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentCcpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_ccpp
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKey(OssComponentCcpp record);
}