package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentVuln;
import com.zbg.secyun.domain.OssComponentVulnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OssComponentVulnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int countByExample(OssComponentVulnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int deleteByExample(OssComponentVulnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int insert(OssComponentVuln record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int insertSelective(OssComponentVuln record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    List<OssComponentVuln> selectByExample(OssComponentVulnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    OssComponentVuln selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentVuln record, @Param("example") OssComponentVulnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int updateByExample(@Param("record") OssComponentVuln record, @Param("example") OssComponentVulnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentVuln record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_vuln
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    int updateByPrimaryKey(OssComponentVuln record);
}