package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.OssComponentJava;
import com.zbg.secyun.domain.OssComponentJavaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssComponentJavaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int countByExample(OssComponentJavaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByExample(OssComponentJavaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insert(OssComponentJava record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int insertSelective(OssComponentJava record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    List<OssComponentJava> selectByExample(OssComponentJavaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    OssComponentJava selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") OssComponentJava record, @Param("example") OssComponentJavaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByExample(@Param("record") OssComponentJava record, @Param("example") OssComponentJavaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKeySelective(OssComponentJava record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_component_java
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    int updateByPrimaryKey(OssComponentJava record);
}