package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.VulnCwe;
import com.zbg.secyun.domain.VulnCweExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VulnCweMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int countByExample(VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int deleteByExample(VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int insert(VulnCwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int insertSelective(VulnCwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    List<VulnCwe> selectByExampleWithBLOBs(VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    List<VulnCwe> selectByExample(VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    VulnCwe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") VulnCwe record, @Param("example") VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") VulnCwe record, @Param("example") VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByExample(@Param("record") VulnCwe record, @Param("example") VulnCweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByPrimaryKeySelective(VulnCwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(VulnCwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_cwe
     *
     * @mbggenerated Sat Jul 31 13:53:33 CST 2021
     */
    int updateByPrimaryKey(VulnCwe record);
}