package com.zbg.secyun.mapper;

import com.zbg.secyun.domain.VulnOCpe;
import com.zbg.secyun.domain.VulnOCpeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VulnOCpeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int countByExample(VulnOCpeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int deleteByExample(VulnOCpeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int insert(VulnOCpe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int insertSelective(VulnOCpe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    List<VulnOCpe> selectByExample(VulnOCpeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    VulnOCpe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") VulnOCpe record, @Param("example") VulnOCpeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int updateByExample(@Param("record") VulnOCpe record, @Param("example") VulnOCpeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int updateByPrimaryKeySelective(VulnOCpe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuln_o_cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    int updateByPrimaryKey(VulnOCpe record);
}