package com.zbg.secyun.domain;

import java.util.Date;

public class OssComponentJs  extends Component{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.language
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.name
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.version
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.md5
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.sha1
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private String sha1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.is_sure
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private Boolean isSure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.created
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_js.category_id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.id
     *
     * @return the value of oss_component_js.id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.id
     *
     * @param id the value for oss_component_js.id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.language
     *
     * @return the value of oss_component_js.language
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.language
     *
     * @param language the value for oss_component_js.language
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.name
     *
     * @return the value of oss_component_js.name
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.name
     *
     * @param name the value for oss_component_js.name
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.version
     *
     * @return the value of oss_component_js.version
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.version
     *
     * @param version the value for oss_component_js.version
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.md5
     *
     * @return the value of oss_component_js.md5
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.md5
     *
     * @param md5 the value for oss_component_js.md5
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.sha1
     *
     * @return the value of oss_component_js.sha1
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public String getSha1() {
        return sha1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.sha1
     *
     * @param sha1 the value for oss_component_js.sha1
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setSha1(String sha1) {
        this.sha1 = sha1 == null ? null : sha1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.is_sure
     *
     * @return the value of oss_component_js.is_sure
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public Boolean getIsSure() {
        return isSure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.is_sure
     *
     * @param isSure the value for oss_component_js.is_sure
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setIsSure(Boolean isSure) {
        this.isSure = isSure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.created
     *
     * @return the value of oss_component_js.created
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.created
     *
     * @param created the value for oss_component_js.created
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_js.category_id
     *
     * @return the value of oss_component_js.category_id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_js.category_id
     *
     * @param categoryId the value for oss_component_js.category_id
     *
     * @mbggenerated Tue Aug 03 11:05:21 CST 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}