package com.zbg.secyun.domain;

import java.util.Date;

public class OssComponentVuln {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_vuln.id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_vuln.language
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    private Integer language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_vuln.component_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    private Integer componentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_vuln.vuln_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    private Integer vulnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_component_vuln.created
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_vuln.id
     *
     * @return the value of oss_component_vuln.id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_vuln.id
     *
     * @param id the value for oss_component_vuln.id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_vuln.language
     *
     * @return the value of oss_component_vuln.language
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_vuln.language
     *
     * @param language the value for oss_component_vuln.language
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_vuln.component_id
     *
     * @return the value of oss_component_vuln.component_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public Integer getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_vuln.component_id
     *
     * @param componentId the value for oss_component_vuln.component_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_vuln.vuln_id
     *
     * @return the value of oss_component_vuln.vuln_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public Integer getVulnId() {
        return vulnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_vuln.vuln_id
     *
     * @param vulnId the value for oss_component_vuln.vuln_id
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public void setVulnId(Integer vulnId) {
        this.vulnId = vulnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_component_vuln.created
     *
     * @return the value of oss_component_vuln.created
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_component_vuln.created
     *
     * @param created the value for oss_component_vuln.created
     *
     * @mbggenerated Mon Aug 02 19:21:34 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}