package com.zbg.secyun.domain;

import java.util.Date;

public class OssOperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_operation_log.id
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_operation_log.operation_desc
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    private String operationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_operation_log.operation_number
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    private Integer operationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_operation_log.create_time
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_operation_log.id
     *
     * @return the value of oss_operation_log.id
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_operation_log.id
     *
     * @param id the value for oss_operation_log.id
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_operation_log.operation_desc
     *
     * @return the value of oss_operation_log.operation_desc
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public String getOperationDesc() {
        return operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_operation_log.operation_desc
     *
     * @param operationDesc the value for oss_operation_log.operation_desc
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public void setOperationDesc(String operationDesc) {
        this.operationDesc = operationDesc == null ? null : operationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_operation_log.operation_number
     *
     * @return the value of oss_operation_log.operation_number
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public Integer getOperationNumber() {
        return operationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_operation_log.operation_number
     *
     * @param operationNumber the value for oss_operation_log.operation_number
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public void setOperationNumber(Integer operationNumber) {
        this.operationNumber = operationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_operation_log.create_time
     *
     * @return the value of oss_operation_log.create_time
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_operation_log.create_time
     *
     * @param createTime the value for oss_operation_log.create_time
     *
     * @mbggenerated Mon Aug 02 18:16:02 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}