package com.zbg.secyun.domain;

public class VulnACpe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.id
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.cnnvd_no
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String cnnvdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String cpe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.review
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private Integer review;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.part
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.vendor
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.product
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.version
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.update
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String update;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.edition
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String edition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuln_a_cpe.language
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.id
     *
     * @return the value of vuln_a_cpe.id
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.id
     *
     * @param id the value for vuln_a_cpe.id
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.cnnvd_no
     *
     * @return the value of vuln_a_cpe.cnnvd_no
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getCnnvdNo() {
        return cnnvdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.cnnvd_no
     *
     * @param cnnvdNo the value for vuln_a_cpe.cnnvd_no
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setCnnvdNo(String cnnvdNo) {
        this.cnnvdNo = cnnvdNo == null ? null : cnnvdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.cpe
     *
     * @return the value of vuln_a_cpe.cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getCpe() {
        return cpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.cpe
     *
     * @param cpe the value for vuln_a_cpe.cpe
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setCpe(String cpe) {
        this.cpe = cpe == null ? null : cpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.review
     *
     * @return the value of vuln_a_cpe.review
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public Integer getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.review
     *
     * @param review the value for vuln_a_cpe.review
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setReview(Integer review) {
        this.review = review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.part
     *
     * @return the value of vuln_a_cpe.part
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.part
     *
     * @param part the value for vuln_a_cpe.part
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.vendor
     *
     * @return the value of vuln_a_cpe.vendor
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.vendor
     *
     * @param vendor the value for vuln_a_cpe.vendor
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setVendor(String vendor) {
        this.vendor = vendor == null ? null : vendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.product
     *
     * @return the value of vuln_a_cpe.product
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.product
     *
     * @param product the value for vuln_a_cpe.product
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.version
     *
     * @return the value of vuln_a_cpe.version
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.version
     *
     * @param version the value for vuln_a_cpe.version
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.update
     *
     * @return the value of vuln_a_cpe.update
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.update
     *
     * @param update the value for vuln_a_cpe.update
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setUpdate(String update) {
        this.update = update == null ? null : update.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.edition
     *
     * @return the value of vuln_a_cpe.edition
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.edition
     *
     * @param edition the value for vuln_a_cpe.edition
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setEdition(String edition) {
        this.edition = edition == null ? null : edition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuln_a_cpe.language
     *
     * @return the value of vuln_a_cpe.language
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vuln_a_cpe.language
     *
     * @param language the value for vuln_a_cpe.language
     *
     * @mbggenerated Thu Aug 05 09:28:27 CST 2021
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}